[supabase]
url = "https://your-project-id.supabase.co"
anon_key = "your-anon-key-here"
service_role_key = "your-service-role-key-here"

# Instructions:
# 1. Replace "your-project-id" with your actual Supabase project ID
# 2. Replace "your-anon-key-here" with your actual anonymous key
# 3. Replace "your-service-role-key-here" with your actual service role key
# 
# You can find these values in your Supabase project dashboard:
# Go to Settings > API > Project URL and API Keys